server:
  port: 8881
spring:
  application:
    name: config-demo
  cloud:
    config:
#      uri: http://localhost:8888
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: config-server
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 192.168.1.151
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
#http://localhost:8881/actuator/refresh     post访问/actuator/refresh 接口，会调动consig-server自动刷新配置,